name: DEPLOY

on:
  [ push ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.4

      - name: Set up JDK 11 🔧
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Validate Gradle wrapper ✔️
        uses: gradle/wrapper-validation-action@v1

      - name: Build with Gradle 🛠
        uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: 7.0.2
          arguments: jsBrowserDistribution

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          BRANCH: gh-pages
          FOLDER: shared/build/distributions
